#!/bin/sh

_REQUEST_GET()
{
  URL=$1
  BODY=$(curl -s $URL)
  TEXTBODY="$BODY"
}

_INDEX_OF()
{
    TEXTINDEX=$1
    PARAM=$2
    LISTINDEXOF=$( echo $TEXTINDEX | grep -aob $PARAM | grep -oE '[0-9]+') 
    ARRINDEX=($LISTINDEXOF)
    INDEXOFCURRENT=${ARRINDEX[0]}
    echo "$INDEXOFCURRENT"
}

_SUBSTRING()
{
    POSITION=$1
    FLOOR=$2
    TEXT=$3

    SUBSTRINGCURRENT="${TEXT:POSITION:FLOOR}"
}

_LENGTH()
{
    LENGTHVARIABLE=$1
    STRLENGTHCURRENT=$(echo -n $LENGTHVARIABLE | wc -m)
}

_SCRAP_BLOCK_PAGE()
{
    TEXT=$1
    INDEXON=$2
    INDEXLAST=$3
    
    _INDEX_OF "$TEXT" "$INDEXON"
    _LENGTH "$INDEXON"
    FIRSTINDEX=$INDEXOFCURRENT
    LENGTHFIRSTINDEX=$STRLENGTHCURRENT
    FIRSTINDEX=$(($FIRSTINDEX + $LENGTHFIRSTINDEX))

    _INDEX_OF "$TEXT" "$INDEXLAST"
    LASTINDEX=$INDEXOFCURRENT

    EXIT=$(($LASTINDEX - $FIRSTINDEX))

    _SUBSTRING  $FIRSTINDEX $EXIT "$TEXT"
    BLOCKCURRENT=$SUBSTRINGCURRENT
}

_GET_LOT_PACKAGES_NPM()
{
    NPMCOMPLETE=$1
    _SCRAP_BLOCK_PAGE "$NPMCOMPLETE" "list-vertical-divider" "pane-download-nodejs"
    echo "$BLOCKCURRENT"
}


###
# Main
###
echo "Start of script..."
URL_SITE="https://www.npmjs.com/"
_REQUEST_GET $URL_SITE
_GET_LOT_PACKAGES_NPM "$TEXTBODY"
echo "End of script..."